### ISSUE TITLE
To Do List (Requests go here, bugs/issues DO NOT)

### ISSUE THREAD

**Issue by shibdib** [shibdib/Dramiel#74]
**Current Jobs (Released, in testing)**
- [ ] Standings Support for Auth

**URGENT**
_Nothing ATM_

**Medium Priority**
- [ ] ESI API - https://github.com/shibdib/Dramiel/issues/101

**Low Priority**
- [ ] Recruiting plugin - https://github.com/shibdib/Dramiel/issues/66
- [ ] Hunting Bot - https://github.com/shibdib/Dramiel/issues/14
- [ ] Add Atom support to the RSS Reader

**Completed and passed testing**
- [x] Isk Value (JSON usage for killmails) - https://github.com/shibdib/Dramiel/issues/48
- [x] https://github.com/shibdib/Dramiel/issues/79
- [x] Ability to restrict bot from responding in certain channels
- [x] Auth issues with large guilds
- [x] Multiple Killmails to separate channels - https://github.com/shibdib/Dramiel/issues/63
- [x] Siphon detection overhaul (multi corp support, and no longer matters if you level out silos when you empty them)
- [x] Expand auth to support multiple groups - https://github.com/shibdib/Dramiel/issues/62
- [x] auth queue
- [x] Multi accounts pulling notifications - https://github.com/shibdib/Dramiel/issues/72

**Scrapped**
- [x] onMessage queue support

**Comment by rufjame** [comment]
Any chance of having an "allow all but this channel" for the bot to respond?

**Comment by shibdib** [comment]
sure, added to the list

**Comment by shibdib** [comment]
@rufjame added https://github.com/shibdib/Dramiel/commit/e419d769df7ccf654f49e7fe1b56aa79c6661515

**Comment by CokkocZateki** [comment]
#79 works well. so far no problems.

**Comment by freeziepopz** [comment]
Any chance in getting kills with supers/caps on it to ping the channel and give the jump route from pre configured "Home" System, or atleast Light years away from pre configured system? No just kills your corp/alliance are on, just kms in general

**Comment by shibdib** [comment]
Not likely. That's a lot of code for a very niche feature.

**Comment by shibdib** [comment]
**NEW** Current Jobs (Released, in testing)

Siphon detection overhaul (multi corp support, and no longer matters if you level out silos when you empty them)


Let me know if anyone encounters any issues

**Comment by shibdib** [comment]
**NEW** Current Jobs (Released, in testing)

 Expand auth to support multiple groups - #62

**Comment by rufjame** [comment]
With the 'eventual' removal of Pos' are there any plans in the pipe line for Citadel and Engineering Complex fuel notifications?

**Comment by shibdib** [comment]
Citadel ones should exist already. I'll have to double check but I believe
I added the notification already

**Comment by rufjame** [comment]
There's an eve notification for when services shutdown but I haven't seen one for the 24hour mark.

**Comment by shibdib** [comment]
I'll do some digging. Does one pop up in game? And if so does the bot post
it saying to make a github issue with this info etc.. Etc..

**Comment by rufjame** [comment]
Engineering Complexes give a notification when the services shutdown and
that's it lol. It's possible to see the fuel hangar from the corporate
asset API though.

**Comment by shibdib** [comment]
That's annoying but can make that work.

**Comment by ZimmerA** [comment]
Hi, can u add support for multiple roles per group? I fiddled something together but i think it would be nice to have it officially supported.

I'll put my code down below.

```
if ($corpID === $authGroup['corpID']) {
    foreach ($roles as $role) {
        foreach($authGroup['corpMemberRole'] as $discordRole){
		if($role->name == $discordRole){
	            $member->addRole($role);
		    $corpRoleSet = 1;
		}
	}
    }
}
```

This should replace line 184-191 in auth.php(note that alliance also has to be done if you  want multiple alliance roles). 
Obviously you have to change the  corpMemberRole in config.php to be an array of strings.

This works as far as that the bot sets multiple roles in discord, however i have no idea if this affects any of the other plugins since it was just a quick solution.

Greetings

**Comment by shibdib** [comment]
when would something like that be used? If everyone gets the same 4 roles it's no different permissions wise than if everyone got 1 role

**Comment by ZimmerA** [comment]
You're right... I was thinking the wrong way because of the way our CEO setup Discord before we used your bot.

In case you're interested:
Our corp had the roles: "Council", "Member", "CEO" and "Corp".
When we manually did them we added the members to "Corp" and "Member" the CEO to "CEO" and "Corp" and so on. This would allow us to do @corp and reach every corp member of every group.
What we could have just done is add the CEO and council to "Member" too. I didn't think of that because our member role has a very specific name.

Thanks for clearing this up.

**Comment by shibdib** [comment]
Yup was confused, although just gave me the idea of auto giving out ceo roles :P

**Comment by nizzan** [comment]
ToDo/Tickets
The ability to:
!nticket Task 1 | Someone needs to do x -> this creates a New ticket with Task 1 being the title and the text after being the description.
!atickte Task 1 | Me -> This assigns the task to me
!cticket Task 1 | Done -> this closes the ticket marking it with a solution of "Done"
!lticket -> list tickets

Thoughts?

**Comment by shibdib** [comment]
That's starting to get outside of the scope I was aiming for in making an eve bot. Not sure how a ticket system is eve related

**Comment by CokkocZateki** [comment]
Can i request that the SSO function also works so that Alliance/Corp Blues can use the service. Currently we have to add the corp to the config file.

@shibdib

**Comment by Aarondorn2** [comment]
Another feature request:

As a bot admin, I would like to configure the mail plugin to post personal mails to a given character to a channel ID, so that I can have an in-game-character that represents the bot.

We have a character with the same name as the bot in-game and would like to be able to send personal mails to it and have those posted to a channel - not just mails from the corp/alliance.

o7

**Comment by shibdib** [comment]
Mmmm I can probably do something along the lines of, every mail a certain API Key gets is posted.

**Comment by Aarondorn2** [comment]
That would work.  It's kinda cool having the bot tie in to the game with an actual character - but Im not sure if that's something that would be widely used among other users. So maybe a low priority?

**Comment by CokkocZateki** [comment]
well with Alpha clones it could become more popular to do something like that

**Comment by shibdib** [comment]
low priority but super easy to implement. Basically just turning off the filter.

**Comment by BroodLK** [comment]
If using both Corp and Alliance auth settings and someone leaves alliance and re-auths with corp. It does not remove the alliance role. It does however properly add the corp role.

**Comment by rufjame** [comment]
very low priority but any chance of blacklisting users from being able to use the bot? Namely other bots that /tableflip whenever someone unflips it. Makes for an interesting channel for a while....

**Comment by nizzan** [comment]
Multi-Corp support for fuel notifications.
We have a few alt-corps we'd like to see the fuel notifications of in the same channel as our main corp.

**Comment by IronWarjack** [comment]
Didn't see this listed.  The bot responds with the info back to the current channel publicly.  And, while not a horrible thing, we suddenly find the channel bogged with everyone doing time checks, char, tq, etc.  We use to use a slack version that did the same things, but it returned as a private message to the user.  We'd love a flag that can turn this feature on (for those who want it).
